development:
  cloud_name: ngocquyhoang
  api_key: '811322267441941'
  api_secret: uxzhbP4kKvzLZVXalo-PQO9-bAA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ngocquyhoang
  api_key: '811322267441941'
  api_secret: uxzhbP4kKvzLZVXalo-PQO9-bAA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ngocquyhoang
  api_key: '811322267441941'
  api_secret: uxzhbP4kKvzLZVXalo-PQO9-bAA
  enhance_image_tag: true
  static_image_support: false